### PR TITLE
Updates from ESS

### PR DESCRIPTION
**Pull request by mac-kan**
Merges the updates from ESS.

### CODE REVIEW

**Comment by anderssandstrom** [comment]
@mac-kan, thanks for the PR.
I'm missing some hardware configuration files (hardware/Beckhoff_3XXX/*.cmd):
* ecmcEL3311.cmd
* ecmcEL3318.cmd
* a few ecmcEL3314_xxxx.cmd
have you by any chance missed those?

**Comment by mac-kan** [comment]
Hi @anderssandstrom,
You are correct. I just verified with Carlos. He added the substitution files as placeholders.
The *.cmd files were not created because we do not have access to the ECMC_EC_PRODUCT_ID.
If you do not want to add the subst-files without the cmd-files, feel free to delete them from the PR.
Is there a way to find out the ECMC_EC_PRODUCT_ID without having the hardware modules themselves?

*Note: Carlos believes that the ECMC_EC_PRODUCT_ID should be the same for all EL3314_xxxx.cmd, but this has not been verified.

Cheers,
Markus & Carlos

**Comment by anderssandstrom** [comment]
@mac-kan, Please clean it up then I take a look again. Thanks!
regarding the ECMC_EC_PRODUCT_ID you can find it in the ESI xml-files used by TwinCAT (in C:\TwinCAT\3.1\Config\Io\EtherCAT\*)
Search for productCode in the appropriate xml file.

**Comment by anderssandstrom** [comment]
Looks nice! Thanks!

**Pull request merged**
