### PR TITLE
Nanotec, Phytron and Leadshine motors review

### PR DESCRIPTION
**Pull request by cdn-lnk**
Hi @anderssandstrom ,

This is my last week at ESS as a consultant.
I am sending the reviews and fixes I had locally before I return the computer.

They mostly focus on Nanotec, Phytron and Leadshine motors with EL7037, EL7047, EL7041 and EL7041-0052 modules (these are the ones I am using lately).

My recommendation is to go commit by commit instead of trying to review everything at once since there are around 150 files 😬 (I organized the commits by motor).

I didn't have time to implement voltage and current macros for all of them but I managed to import the EL7041 configs from EL7047 on all of them and I am using links when the config files would be identical.

I also implemented a voltage check script, but I am not calling it from any motor (yet).

~~Note: I changed the default voltage on some motors. I kept these in a separate commit in case you want to cherry pick them out.~~ (The modules are limited to 48V, see Javier comment below).

Note2: The config for the Leadshine 57HS09 was quite off!!!

FYI: @mac-kan, @javicereijo, @lucianocguedes, @laispc

---

Useful links:

- [Phytron VSS motors manual](https://www.phytron.eu/fileadmin/user_upload/produkte/motoren_aktuatoren/pdf/ds-vacuum-en.pdf)
- [Nanotec website](https://en.nanotec.com)

I could not find the Leadshine manual online, I am uploading it in this comment.
[57hsxxd-hqm.pdf](https://github.com/paulscherrerinstitute/ecmccfg/files/12194218/57hsxxd-hqm.pdf) (thanks Laís).

### CODE REVIEW

**Comment by cdn-lnk** [comment]
Useful links:

- [Phytron VSS motors manual](https://www.phytron.eu/fileadmin/user_upload/produkte/motoren_aktuatoren/pdf/ds-vacuum-en.pdf)
- [Nanotec website](https://en.nanotec.com)

I could not find the Leadshine manual online, I am uploading it in this comment.
[57hsxxd-hqm.pdf](https://github.com/paulscherrerinstitute/ecmccfg/files/12194218/57hsxxd-hqm.pdf)

**Comment by javicereijo** [comment]
@cdn-lnk please check the config for the motors that work at more than 48 V, even if the motors accept more voltage the motor drives (at least the BEckhoff ones that we use in the accelerator) cannot provide more than 48 V.

**Review by mac-kan — COMMENTED** [review]
@cdn-lnk 
general/chkValidCurrentSetOrDie.cmd: Correct spelling - stanby->standby

I saw your commit about removing your name from the motor files since this is taken care of in git anyhow. The convention in this repo has been to have an author stated, will this change for all files or is there a reason for keeping it?

Since we are updating a lot of motor config scripts, please fix the spelling of Parmetrization->Parametrization

**Comment by cdn-lnk** [comment]
Hej @mac-kan,

>  general/chkValidCurrentSetOrDie.cmd: Correct spelling - stanby->standby

Fixed!

> Since we are updating a lot of motor config scripts, please fix the spelling of Parmetrization->Parametrization

Also fixed! Thanks.

> I saw your commit about removing your name from the motor files since this is taken care of in git anyhow. The convention in this repo has been to have an author stated, will this change for all files or is there a reason for keeping it?

I don't have a strong opinion on this.
I can re-add myself as author if needed/necessary/wanted.

**Comment by anderssandstrom** [comment]
Looks nice! Thanks

**Pull request merged**
