### PR TITLE
Jinja2

### PR DESCRIPTION
**Pull request by kivel**
HI Anders

checkout the examples in test/PSI/jinja2. The PLC works for me.

Make sure to add the /scripts/jinja2/* to your build env :)

### CODE REVIEW

**Comment by anderssandstrom** [comment]
Hi Niko, 
Looks very nice!
Not sure the "!" command works for me. Is there some trick to that?
Cheers
A

**Comment by kivel** [comment]
I see, I'll change it to `system`


--
Paul Scherrer Institute
Dr. Niko Kivel
Forschungsstrasse 111
WBGB/017
5232 Villigen PSI
Switzerland

phone: +41 56 310 2226
email: ***@***.***
________________________________

**Comment by kivel** [comment]
@anderssandstrom can you please try to run the loadPLC.iocsh from PSI examples on the ESS environment?

**Comment by anderssandstrom** [comment]
Will do, just need to finalise one thing then I test :-)

**Comment by anderssandstrom** [comment]
I get this

#==============================================================================
# setDiagnostics.cmd
ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
2021/06/22 12:04:31.264 OK
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
2021/06/22 12:04:31.265 OK
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"
2021/06/22 12:04:31.265 OK
epicsEnvSet("ECMCCFG_INIT" ,"#")
iocshLoad "/home/pi/epics/base-7.0.5/require/3.4.0/siteMods/ecmccfg/develop/loadYamlPlc.cmd" "FILE=./plc1.yaml"
system "cp /home/pi/epics/base-7.0.5/require/3.4.0/siteMods/ecmccfg/develop/requirements.txt /tmp/IOC_TEST/EcMaster_-1/"
cp: cannot create regular file '/tmp/IOC_TEST/EcMaster_-1/requirements.txt': Permission denied
system "/home/pi/epics/base-7.0.5/require/3.4.0/siteMods/ecmccfg/develop/pythonVenvJinja2.sh -d /tmp/IOC_TEST/EcMaster_-1/ -t /home/pi/epics/base-7.0.5/require/3.4.0/siteMods/ecmccfg/develop/plc.jinja2 -D ./plc1.yaml -o /tmp/IOC_TEST/EcMaster_-1/./plc1.yaml.plc"
Traceback (most recent call last):
  File "/home/pi/.local/bin/jinja2", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python2.7/site-packages/jinja2cli/cli.py", line 424, in main
    sys.exit(cli(opts, args))
  File "/home/pi/.local/lib/python2.7/site-packages/jinja2cli/cli.py", line 260, in cli
    raise InvalidDataFormat(ext)
jinja2cli.cli.InvalidDataFormat: yaml
ecmcFileExist("/tmp/IOC_TEST/EcMaster_-1/./plc1.yaml.plc",1)
Error: File "/tmp/IOC_TEST/EcMaster_-1/./plc1.yaml.plc" does not exist. ECMC shuts down.
       Current working directory           = /home/pi/sources/e3-7.0.5/ecat/e3-ecmccfg/ecmccfg-dev/examples/test/PSI/jinja2

Guess I should use python 3 instead?
then I also have an issue with the cp of requirements.txt. Will work first time but fails second time because file is already there  and write protected.

**Comment by anderssandstrom** [comment]
forgot to install yaml :-) now it works!

**Comment by anderssandstrom** [comment]
Still I get this:
```
system "cp /home/pi/epics/base-7.0.5/require/3.4.0/siteMods/ecmccfg/develop/requirements.txt /tmp/IOC_TEST/EcMaster_-1/"
cp: cannot create regular file '/tmp/IOC_TEST/EcMaster_-1/requirements.txt': Permission denied

```

**Comment by kivel** [comment]
The problem seems to be that the privileges lacking to write to /tmp.

you can try this. It sets the location for temporary files
`${SCRIPTEXEC} "${ECMC_CONFIG_ROOT}loadYamlPlc.cmd" "FILE=./plc1.yaml, TMP_DIR=<dir with rw>"`

**Comment by anderssandstrom** [comment]
Well yes/no.. it writes fine the first time but then overwriting is not allowed. Seems user looses the write permission to req*.txt when its installed.

**Comment by kivel** [comment]
@anderssandstrom I removed the `requirements.txt`.
You _don't_ need jinja2-cli or pyyaml on the system. The script will create a virtual environment and execute the `jinja2` command within.
Still weird the users looses write permission to `/tmp`.

**Comment by anderssandstrom** [comment]
Jinja,yaml:
OK, then it did not work for me because I had something like "jinja2" command not found. I will check again.

write permission:
So all files that are installed in E3 seems to get "-r-xr-xr-x", so I guess that's why it can be copied once but not overwritten?

**Comment by kivel** [comment]
can you issue those commands manually on this system?
```
python3 -m venv "${ENV_DIR}"
source "${ENV_DIR}"/bin/activate
pip3 install pyyaml jinja2-cli
```

**Comment by anderssandstrom** [comment]
I get this:
python3 -m venv "${ENV_DIR}"
Error: Command '['/tmp/.venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

**Comment by kivel** [comment]
That looks like you're missing `python-venv`, or however the package is called on your particular OS.


What is the ESS way to handle dependencies like that. Do you favour installing it on the bare-metal, or do you favour virtual environments?

Is your default still python2.7?


I'd like to involve python more in ecmccfg, but for that we'd need a common ground.


Niko


--
Paul Scherrer Institute
Dr. Niko Kivel
Forschungsstrasse 111
WBGB/017
5232 Villigen PSI
Switzerland

phone: +41 56 310 2226
email: ***@***.***
________________________________

**Comment by anderssandstrom** [comment]
Ok, I'll try to install venv.
Currently I only have a raspi at home for tests and on that one 2.7 is default. However I think we also have 2.7 default in or centos. I normally use conda to make an environment with 3.x but seems venv is simpler..

**Comment by kivel** [comment]
@anderssandstrom I'd argue that with python3 is mature enough to be considered 'standard'. But, if you have a policy at ESS that will restrict us to 2.7. I'll find a way to make it happen.

I made some changes to allow not only PLCs to be defined inside the yaml, but also use the yaml as config descriptor/header and load from a conventional PLC-file. The PLC-files are much easier to read and maintain. They also have the benefit of regular ';' instead of '|' endline identifiers, which are a still a little weird.
The 'file: ' in the yaml describes which file to load, with MACROS in the PLC-file, this allows for generic PLC-files as they subsequently will pass through iocshLoad for macro substitution.
if there is 'code: ' _and_ 'file: ' in the yaml, the PLC-file will **substitute** the code _not_ append to it.

**Comment by kivel** [comment]
@anderssandstrom
The last commit contains a working yaml-config for an AM8111 servo. I have no real axis at hand right now for proper testing.
I hope I covered most in the sanity check and picked reasonable defaults elsewhere.
Please take a look the `axisConfig.adoc` in examples/test/PSI/jinja2

**Pull request merged**
