### PR TITLE
AMI8000

### PR DESCRIPTION
**Pull request by kivel**
@anderssandstrom 

I added an AMI8121 to ecmccfg.
It's still a bit flaky at low velocities.

### CODE REVIEW

**Comment by anderssandstrom** [comment]
Nice!

**Comment by kivel** [comment]
Any idea what ErrID: 83541, `E: ERROR_DRV_DS402_FAULT_STATE (0x14655` might be?

**Comment by anderssandstrom** [comment]
DS402 state machine in error state. Could be wrong control parameters or some setting.. Hard to say. When do you get it? When enabling?

**Comment by kivel** [comment]
mid move, sometimes at when approaching the target position, or even when the move completed and the servo is just holding position.

I need to investigate a bit more to derive a pattern.


--
Paul Scherrer Institute
Dr. Niko Kivel
Forschungsstrasse 111
WBGB/017
5232 Villigen PSI
Switzerland

phone: +41 56 310 2226
email: ***@***.***
________________________________

**Pull request merged**
