### PR TITLE
Remove ess examples

### PR DESCRIPTION
**Pull request by cdn-lnk**
Hi @kivel , 

This PR removes a few example folders. All of them ESS related.

They are somewhat old and do not reflect the current state of the system or ecmc/ecmccfg.

I don't think they are (and probably should not) being used by anybody.

Also since I'm the integrator for all the systems removed, if you believe fit, we can re-include them as sub modules. This way we would keep examples but we don't get all of them cloned by default and easier to update as newer versions are released.

Let me know what you think.

### CODE REVIEW

**Review by kivel — APPROVED** [review]
I approve this PR for the deletion.
I'm hesitant about the submodules, though. Where will the submodules be hosted? As part of the `paulscherrerinstitute` organization?

**Comment by cdn-lnk** [comment]
The submodules are hosted on ESS gitlab.

Technically, it is possible. just use `git clone --recursive` and you get the files.
Github web interface will not redirect to ESS gitlab though.

But I'm ok if you prefer not re-introducing them.

**Comment by anderssandstrom** [comment]
I prefer to not add any submodules

**Comment by kivel** [comment]
I'm with Anders, cross facility and git-provider submodules will be a challenge.
Why don't we add a section in the docs that point to examples? There could be links to the ESS-gitlab as well.

**Pull request merged**
